---
dataset:
  name: ERA5
  store: cds

variables:
  varname: cbh
  freq: 1D
  family: E5
  level: sf

paths:
  origin: derived-era5-single-levels-daily-statistics
  download: /net/nitrogen/c2sm-scratch/rlorenz/era5_cds
  work: /net/nitrogen/c2sm-scratch/rlorenz/era5_cds/work
  proc: /net/atmos/data/era5_cds/processed/v2/

time:
  startyr: 2024
  endyr: 2024
  months: 03, 04, 05, 06, 07, 08, 09, 10, 11, 12 # list of months to be processed, if not given everything available is processed

chunking:
  time_chk: 1
  lat_chk: 46
  lon_chk: 22

flags:
  overwrite: False

